name: Auto-Deploy to Parakeet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŒ¥ï¸ Checkout
        uses: actions/checkout@v2
      - name: ğŸ“¦ Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: ğŸ” Prerequisites
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: ğŸ§° Dependencies
        run: yarn install --prefer-offline --pure-lockfile
      - name: ğŸ”¨ Build
        run: yarn build
      - name: ğŸ¦œ Deploy
        id: deploy-netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=out --prod